// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>dacpac</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace GOEddie.DacpacApi {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02", IsNullable=false)]
    public partial class DataSchemaModel {
        
        private List<HeaderTypeCustomData> headerField;
        
        private List<object> modelField;
        
        private decimal fileFormatVersionField;
        
        private decimal schemaVersionField;
        
        private string dspNameField;
        
        private ushort collationLcidField;
        
        private string collationCaseSensitiveField;
        
        public DataSchemaModel() {
            this.modelField = new List<object>();
            this.headerField = new List<HeaderTypeCustomData>();
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("CustomData", IsNullable=false)]
        public List<HeaderTypeCustomData> Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("Annotation", typeof(AnnotationType), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AttachedAnnotation", typeof(AnnotationReferenceType), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Element", typeof(ElementType), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Unattached", typeof(ModelTypeUnattached), IsNullable=false)]
        public List<object> Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal FileFormatVersion {
            get {
                return this.fileFormatVersionField;
            }
            set {
                this.fileFormatVersionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal SchemaVersion {
            get {
                return this.schemaVersionField;
            }
            set {
                this.schemaVersionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DspName {
            get {
                return this.dspNameField;
            }
            set {
                this.dspNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort CollationLcid {
            get {
                return this.collationLcidField;
            }
            set {
                this.collationLcidField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CollationCaseSensitive {
            get {
                return this.collationCaseSensitiveField;
            }
            set {
                this.collationCaseSensitiveField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    public partial class HeaderTypeCustomData {
        
        private List<HeaderTypeCustomDataMetadata> metadataField;
        
        private string categoryField;
        
        private string typeField;
        
        public HeaderTypeCustomData() {
            this.metadataField = new List<HeaderTypeCustomDataMetadata>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Metadata")]
        public List<HeaderTypeCustomDataMetadata> Metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    public partial class HeaderTypeCustomDataMetadata {
        
        private string nameField;
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02", IsNullable=true)]
    public partial class PositionType {
        
        private string isPrimaryField;
        
        private int offsetField;
        
        private int lengthField;
        
        private int lineField;
        
        private int columnField;
        
        private string sourceNameField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IsPrimary {
            get {
                return this.isPrimaryField;
            }
            set {
                this.isPrimaryField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Column {
            get {
                return this.columnField;
            }
            set {
                this.columnField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SourceName {
            get {
                return this.sourceNameField;
            }
            set {
                this.sourceNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02", IsNullable=true)]
    public partial class ReferencesType {
        
        private string externalSourceField;
        
        private string nameField;
        
        private string typeField;
        
        private string disambiguatorField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ExternalSource {
            get {
                return this.externalSourceField;
            }
            set {
                this.externalSourceField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Disambiguator {
            get {
                return this.disambiguatorField;
            }
            set {
                this.disambiguatorField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02", IsNullable=true)]
    public partial class RelationshipType {
        
        private List<object> entryField;
        
        private string nameField;
        
        public RelationshipType() {
            this.entryField = new List<object>();
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("Annotation", typeof(AnnotationType), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AttachedAnnotation", typeof(AnnotationReferenceType), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Element", typeof(ElementType), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Position", typeof(PositionType), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("References", typeof(ReferencesType), IsNullable=false)]
        public List<object> Entry {
            get {
                return this.entryField;
            }
            set {
                this.entryField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02", IsNullable=true)]
    public partial class AnnotationType {
        
        private List<PropertyType> propertyField;
        
        private string typeField;
        
        private string nameField;
        
        private string disambiguatorField;
        
        public AnnotationType() {
            this.propertyField = new List<PropertyType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Property")]
        public List<PropertyType> Property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Disambiguator {
            get {
                return this.disambiguatorField;
            }
            set {
                this.disambiguatorField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02", IsNullable=true)]
    public partial class PropertyType {
        
        private PropertyTypeValue valueField;
        
        private string nameField;
        
        private string value1Field;
        
        public PropertyType() {
            this.valueField = new PropertyTypeValue();
        }
        
        public PropertyTypeValue Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Value")]
        public string Value1 {
            get {
                return this.value1Field;
            }
            set {
                this.value1Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    public partial class PropertyTypeValue {
        
        private bool quotedIdentifiersField;
        
        private bool quotedIdentifiersFieldSpecified;
        
        private bool ansiNullsField;
        
        private bool ansiNullsFieldSpecified;
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool QuotedIdentifiers {
            get {
                return this.quotedIdentifiersField;
            }
            set {
                this.quotedIdentifiersField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuotedIdentifiersSpecified {
            get {
                return this.quotedIdentifiersFieldSpecified;
            }
            set {
                this.quotedIdentifiersFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AnsiNulls {
            get {
                return this.ansiNullsField;
            }
            set {
                this.ansiNullsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnsiNullsSpecified {
            get {
                return this.ansiNullsFieldSpecified;
            }
            set {
                this.ansiNullsFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02", IsNullable=true)]
    public partial class AnnotationReferenceType {
        
        private string disambiguatorField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Disambiguator {
            get {
                return this.disambiguatorField;
            }
            set {
                this.disambiguatorField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02", IsNullable=true)]
    public partial class ElementType {
        
        private List<object> itemsField;
        
        private string typeField;
        
        private string nameField;
        
        private string disambiguatorField;
        
        public ElementType() {
            this.itemsField = new List<object>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Annotation", typeof(AnnotationType))]
        [System.Xml.Serialization.XmlElementAttribute("AttachedAnnotation", typeof(AnnotationReferenceType))]
        [System.Xml.Serialization.XmlElementAttribute("Position", typeof(PositionType))]
        [System.Xml.Serialization.XmlElementAttribute("Property", typeof(PropertyType))]
        [System.Xml.Serialization.XmlElementAttribute("Relationship", typeof(RelationshipType))]
        public List<object> Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Disambiguator {
            get {
                return this.disambiguatorField;
            }
            set {
                this.disambiguatorField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    public partial class ModelTypeUnattached {
        
        private List<AnnotationType> annotationField;
        
        public ModelTypeUnattached() {
            this.annotationField = new List<AnnotationType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Annotation")]
        public List<AnnotationType> Annotation {
            get {
                return this.annotationField;
            }
            set {
                this.annotationField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02", IsNullable=false)]
    public partial class DacType {
        
        private string nameField;
        
        private string versionField;
        
        private string descriptionField;
        
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02", IsNullable=false)]
    public partial class DacOrigin {
        
        private DacOriginPackageProperties packagePropertiesField;
        
        private DacOriginOperation operationField;
        
        private DacOriginServer serverField;
        
        private DacOriginExportStatistics exportStatisticsField;
        
        private List<DacOriginChecksum> checksumsField;
        
        public DacOrigin() {
            this.checksumsField = new List<DacOriginChecksum>();
            this.exportStatisticsField = new DacOriginExportStatistics();
            this.serverField = new DacOriginServer();
            this.operationField = new DacOriginOperation();
            this.packagePropertiesField = new DacOriginPackageProperties();
        }
        
        public DacOriginPackageProperties PackageProperties {
            get {
                return this.packagePropertiesField;
            }
            set {
                this.packagePropertiesField = value;
            }
        }
        
        public DacOriginOperation Operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
        
        public DacOriginServer Server {
            get {
                return this.serverField;
            }
            set {
                this.serverField = value;
            }
        }
        
        public DacOriginExportStatistics ExportStatistics {
            get {
                return this.exportStatisticsField;
            }
            set {
                this.exportStatisticsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("Checksum", IsNullable=false)]
        public List<DacOriginChecksum> Checksums {
            get {
                return this.checksumsField;
            }
            set {
                this.checksumsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    public partial class DacOriginPackageProperties {
        
        private string versionField;
        
        private string containsExportedDataField;
        
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        public string ContainsExportedData {
            get {
                return this.containsExportedDataField;
            }
            set {
                this.containsExportedDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    public partial class DacOriginOperation {
        
        private string identityField;
        
        private string startField;
        
        private string endField;
        
        private string productNameField;
        
        private string productVersionField;
        
        private string productSchemaField;
        
        public string Identity {
            get {
                return this.identityField;
            }
            set {
                this.identityField = value;
            }
        }
        
        public string Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        public string End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
        
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        public string ProductVersion {
            get {
                return this.productVersionField;
            }
            set {
                this.productVersionField = value;
            }
        }
        
        public string ProductSchema {
            get {
                return this.productSchemaField;
            }
            set {
                this.productSchemaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    public partial class DacOriginServer {
        
        private string serverVersionField;
        
        private DacOriginServerObjectCounts objectCountsField;
        
        public DacOriginServer() {
            this.objectCountsField = new DacOriginServerObjectCounts();
        }
        
        public string ServerVersion {
            get {
                return this.serverVersionField;
            }
            set {
                this.serverVersionField = value;
            }
        }
        
        public DacOriginServerObjectCounts ObjectCounts {
            get {
                return this.objectCountsField;
            }
            set {
                this.objectCountsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    public partial class DacOriginServerObjectCounts {
        
        private List<int> itemsField;
        
        private List<ItemsChoiceType> itemsElementNameField;
        
        public DacOriginServerObjectCounts() {
            this.itemsElementNameField = new List<ItemsChoiceType>();
            this.itemsField = new List<int>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Aggregate", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("ApplicationRole", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Assembly", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("AssemblyFile", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("AssemblySource", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("AsymmetricKey", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("AuditAction", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("AuditActionGroup", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("AuditActionSpecification", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("BrokerPriority", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("BuiltInServerRole", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("BuiltInType", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Certificate", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("CheckConstraint", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("ClrFunctionImplementation", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("ClrFunctionOrderedColumnSpecification", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("ClrMethod", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("ClrMethodParameter", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("ClrProperty", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("ColumnSet", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("ColumnStoreIndex", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("ComputedColumn", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Contract", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Credential", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("CryptographicProvider", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("DataCompressionOption", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("DatabaseAuditSpecification", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("DatabaseDdlTrigger", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("DatabaseEncryptionKey", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("DatabaseEventNotification", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("DatabaseOptions", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Default", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("DefaultConstraint", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("DmlTrigger", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("DynamicColumnSource", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Endpoint", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("ErrorMessage", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("EventSession", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("EventSessionAction", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("EventSessionDefinitions", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("EventSessionSetting", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("EventSessionTarget", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("ExtendedProcedure", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("ExtendedProperty", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("File", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("FileTable", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Filegroup", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("ForeignKeyConstraint", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("FullTextCatalog", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("FullTextIndex", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("FullTextStopList", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Index", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("InlineTableValuedFunction", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("LinkedServer", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("LinkedServerLogin", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Login", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("MasterKey", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("MessageType", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("MultiStatementTableValuedFunction", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("PartitionFunction", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("PartitionScheme", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("PartitionValue", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("PermissionStatement", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("PrimaryKeyConstraint", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Procedure", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Queue", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("QueueEventNotification", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("RemoteServiceBinding", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("ResourceGovernor", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("ResourcePool", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Role", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("RoleMembership", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Route", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Rule", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("ScalarFunction", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Schema", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Script", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("ScriptFunctionImplementation", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("SearchProperty", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("SearchPropertyList", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Sequence", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("ServerAudit", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("ServerAuditSpecification", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("ServerDdlTrigger", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("ServerEventNotification", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("ServerOptions", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("ServerRoleMembership", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Service", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Signature", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("SignatureEncryptionMechanism", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("SimpleColumn", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("SoapMethodSpecification", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("SpatialIndex", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Statistic", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("SubroutineParameter", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("SymmetricKey", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("SymmetricKeyEncryptionPassword", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Synonym", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Table", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("TableType", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("TableTypeCheckConstraint", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("TableTypeComputedColumn", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("TableTypeDefaultConstraint", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("TableTypeIndexedColumnSpecification", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("TableTypePrimaryKeyConstraint", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("TableTypeSimpleColumn", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("TableTypeUniqueConstraint", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("UniqueConstraint", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("User", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("UserDefinedDataType", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("UserDefinedServerRole", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("UserDefinedType", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("View", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("WorkloadGroup", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("XmlIndex", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("XmlSchemaCollection", typeof(int))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public List<int> Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public List<ItemsChoiceType> ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        Aggregate,
        
        /// <remarks/>
        ApplicationRole,
        
        /// <remarks/>
        Assembly,
        
        /// <remarks/>
        AssemblyFile,
        
        /// <remarks/>
        AssemblySource,
        
        /// <remarks/>
        AsymmetricKey,
        
        /// <remarks/>
        AuditAction,
        
        /// <remarks/>
        AuditActionGroup,
        
        /// <remarks/>
        AuditActionSpecification,
        
        /// <remarks/>
        BrokerPriority,
        
        /// <remarks/>
        BuiltInServerRole,
        
        /// <remarks/>
        BuiltInType,
        
        /// <remarks/>
        Certificate,
        
        /// <remarks/>
        CheckConstraint,
        
        /// <remarks/>
        ClrFunctionImplementation,
        
        /// <remarks/>
        ClrFunctionOrderedColumnSpecification,
        
        /// <remarks/>
        ClrMethod,
        
        /// <remarks/>
        ClrMethodParameter,
        
        /// <remarks/>
        ClrProperty,
        
        /// <remarks/>
        ColumnSet,
        
        /// <remarks/>
        ColumnStoreIndex,
        
        /// <remarks/>
        ComputedColumn,
        
        /// <remarks/>
        Contract,
        
        /// <remarks/>
        Credential,
        
        /// <remarks/>
        CryptographicProvider,
        
        /// <remarks/>
        DataCompressionOption,
        
        /// <remarks/>
        DatabaseAuditSpecification,
        
        /// <remarks/>
        DatabaseDdlTrigger,
        
        /// <remarks/>
        DatabaseEncryptionKey,
        
        /// <remarks/>
        DatabaseEventNotification,
        
        /// <remarks/>
        DatabaseOptions,
        
        /// <remarks/>
        Default,
        
        /// <remarks/>
        DefaultConstraint,
        
        /// <remarks/>
        DmlTrigger,
        
        /// <remarks/>
        DynamicColumnSource,
        
        /// <remarks/>
        Endpoint,
        
        /// <remarks/>
        ErrorMessage,
        
        /// <remarks/>
        EventSession,
        
        /// <remarks/>
        EventSessionAction,
        
        /// <remarks/>
        EventSessionDefinitions,
        
        /// <remarks/>
        EventSessionSetting,
        
        /// <remarks/>
        EventSessionTarget,
        
        /// <remarks/>
        ExtendedProcedure,
        
        /// <remarks/>
        ExtendedProperty,
        
        /// <remarks/>
        File,
        
        /// <remarks/>
        FileTable,
        
        /// <remarks/>
        Filegroup,
        
        /// <remarks/>
        ForeignKeyConstraint,
        
        /// <remarks/>
        FullTextCatalog,
        
        /// <remarks/>
        FullTextIndex,
        
        /// <remarks/>
        FullTextStopList,
        
        /// <remarks/>
        Index,
        
        /// <remarks/>
        InlineTableValuedFunction,
        
        /// <remarks/>
        LinkedServer,
        
        /// <remarks/>
        LinkedServerLogin,
        
        /// <remarks/>
        Login,
        
        /// <remarks/>
        MasterKey,
        
        /// <remarks/>
        MessageType,
        
        /// <remarks/>
        MultiStatementTableValuedFunction,
        
        /// <remarks/>
        PartitionFunction,
        
        /// <remarks/>
        PartitionScheme,
        
        /// <remarks/>
        PartitionValue,
        
        /// <remarks/>
        PermissionStatement,
        
        /// <remarks/>
        PrimaryKeyConstraint,
        
        /// <remarks/>
        Procedure,
        
        /// <remarks/>
        Queue,
        
        /// <remarks/>
        QueueEventNotification,
        
        /// <remarks/>
        RemoteServiceBinding,
        
        /// <remarks/>
        ResourceGovernor,
        
        /// <remarks/>
        ResourcePool,
        
        /// <remarks/>
        Role,
        
        /// <remarks/>
        RoleMembership,
        
        /// <remarks/>
        Route,
        
        /// <remarks/>
        Rule,
        
        /// <remarks/>
        ScalarFunction,
        
        /// <remarks/>
        Schema,
        
        /// <remarks/>
        Script,
        
        /// <remarks/>
        ScriptFunctionImplementation,
        
        /// <remarks/>
        SearchProperty,
        
        /// <remarks/>
        SearchPropertyList,
        
        /// <remarks/>
        Sequence,
        
        /// <remarks/>
        ServerAudit,
        
        /// <remarks/>
        ServerAuditSpecification,
        
        /// <remarks/>
        ServerDdlTrigger,
        
        /// <remarks/>
        ServerEventNotification,
        
        /// <remarks/>
        ServerOptions,
        
        /// <remarks/>
        ServerRoleMembership,
        
        /// <remarks/>
        Service,
        
        /// <remarks/>
        Signature,
        
        /// <remarks/>
        SignatureEncryptionMechanism,
        
        /// <remarks/>
        SimpleColumn,
        
        /// <remarks/>
        SoapMethodSpecification,
        
        /// <remarks/>
        SpatialIndex,
        
        /// <remarks/>
        Statistic,
        
        /// <remarks/>
        SubroutineParameter,
        
        /// <remarks/>
        SymmetricKey,
        
        /// <remarks/>
        SymmetricKeyEncryptionPassword,
        
        /// <remarks/>
        Synonym,
        
        /// <remarks/>
        Table,
        
        /// <remarks/>
        TableType,
        
        /// <remarks/>
        TableTypeCheckConstraint,
        
        /// <remarks/>
        TableTypeComputedColumn,
        
        /// <remarks/>
        TableTypeDefaultConstraint,
        
        /// <remarks/>
        TableTypeIndexedColumnSpecification,
        
        /// <remarks/>
        TableTypePrimaryKeyConstraint,
        
        /// <remarks/>
        TableTypeSimpleColumn,
        
        /// <remarks/>
        TableTypeUniqueConstraint,
        
        /// <remarks/>
        UniqueConstraint,
        
        /// <remarks/>
        User,
        
        /// <remarks/>
        UserDefinedDataType,
        
        /// <remarks/>
        UserDefinedServerRole,
        
        /// <remarks/>
        UserDefinedType,
        
        /// <remarks/>
        View,
        
        /// <remarks/>
        WorkloadGroup,
        
        /// <remarks/>
        XmlIndex,
        
        /// <remarks/>
        XmlSchemaCollection,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    public partial class DacOriginExportStatistics {
        
        private int sourceDatabaseSizeField;
        
        private bool sourceDatabaseSizeFieldSpecified;
        
        private int tableRowCountTotalTagField;
        
        private bool tableRowCountTotalTagFieldSpecified;
        
        public int SourceDatabaseSize {
            get {
                return this.sourceDatabaseSizeField;
            }
            set {
                this.sourceDatabaseSizeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SourceDatabaseSizeSpecified {
            get {
                return this.sourceDatabaseSizeFieldSpecified;
            }
            set {
                this.sourceDatabaseSizeFieldSpecified = value;
            }
        }
        
        public int TableRowCountTotalTag {
            get {
                return this.tableRowCountTotalTagField;
            }
            set {
                this.tableRowCountTotalTagField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TableRowCountTotalTagSpecified {
            get {
                return this.tableRowCountTotalTagFieldSpecified;
            }
            set {
                this.tableRowCountTotalTagFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    public partial class DacOriginChecksum {
        
        private string uriField;
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    [System.Xml.Serialization.XmlRootAttribute("Operations", Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02", IsNullable=false)]
    public partial class OperationsType {
        
        private List<OperationType> operationField;
        
        private string versionField;
        
        public OperationsType() {
            this.operationField = new List<OperationType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Operation")]
        public List<OperationType> Operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02", IsNullable=true)]
    public partial class OperationType {
        
        private List<OperationTypeProperty> propertyField;
        
        private OperationTypeName nameField;
        
        private string keyField;
        
        private string changeDateTimeField;
        
        public OperationType() {
            this.propertyField = new List<OperationTypeProperty>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Property")]
        public List<OperationTypeProperty> Property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public OperationTypeName Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ChangeDateTime {
            get {
                return this.changeDateTimeField;
            }
            set {
                this.changeDateTimeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    public partial class OperationTypeProperty {
        
        private OperationTypePropertyName nameField;
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public OperationTypePropertyName Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    public enum OperationTypePropertyName {
        
        /// <remarks/>
        ElementName,
        
        /// <remarks/>
        ElementType,
        
        /// <remarks/>
        ParentElementName,
        
        /// <remarks/>
        ParentElementType,
        
        /// <remarks/>
        NewName,
        
        /// <remarks/>
        NewSchema,
        
        /// <remarks/>
        IsNewSchemaExternal,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    public enum OperationTypeName {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Rename Refactor")]
        RenameRefactor,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Move Schema")]
        MoveSchema,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02", IsNullable=true)]
    public partial class HeaderType {
        
        private List<HeaderTypeCustomData> customDataField;
        
        public HeaderType() {
            this.customDataField = new List<HeaderTypeCustomData>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("CustomData")]
        public List<HeaderTypeCustomData> CustomData {
            get {
                return this.customDataField;
            }
            set {
                this.customDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02", IsNullable=true)]
    public partial class ModelType {
        
        private List<object> itemsField;
        
        public ModelType() {
            this.itemsField = new List<object>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Annotation", typeof(AnnotationType))]
        [System.Xml.Serialization.XmlElementAttribute("AttachedAnnotation", typeof(AnnotationReferenceType))]
        [System.Xml.Serialization.XmlElementAttribute("Element", typeof(ElementType))]
        [System.Xml.Serialization.XmlElementAttribute("Unattached", typeof(ModelTypeUnattached))]
        public List<object> Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
}
